# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish to Releases

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
      with:
         gradle-version: 8.6

    - name: Create wrapper
      run: gradle wrapper

    - name: Make gradlew executible
      run: chmod +x gradlew

    - name: Build API
      run: ./gradlew API:build
    - name: Build Paper
      run: ./gradlew Paper:build
    - name: Build Sponge
      run: ./gradlew Sponge:build
    - name: Build Fabric
      run: ./gradlew Fabric:build

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: "Automatic Dev Build Release."
        draft: false
        prerelease: true
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.sha }}
          prerelease: true
          title: Release ${{ github.sha }}
          files: |
            output/*.jar
