name: Pronouns
version: '0.2.0'
main: net.kore.pronouns.paper.PaperPronouns
api-version: '1.20'
folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false